osx_image: xcode11
language: swift

env:
  global:
  - WORKSPACE=Image360.xcworkspace
  - Image360_SCHEME="Image360"
  - IOS_EXAMPLE_SCHEME="iOS Example"
  matrix:
  - DESTINATION="OS=13.0,name=iPhone 11 Pro"
  - DESTINATION="OS=12.1,name=iPhone 8 Plus"

script:
- set -o pipefail
- xcodebuild -version
- xcodebuild -showsdks

# Build Framework in Debug
- xcodebuild -workspace "$WORKSPACE" -scheme "$Image360_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;

# Build Framework in Release
- xcodebuild -workspace "$WORKSPACE" -scheme "$Image360_SCHEME" -destination "$DESTINATION" -configuration Release ONLY_ACTIVE_ARCH=NO build | xcpretty;

# Build an example project
- xcodebuild -workspace "$WORKSPACE" -scheme "$IOS_EXAMPLE_SCHEME" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build | xcpretty;
